### ISSUE TITLE
dev testing issue

### ISSUE THREAD

**Issue by mikeyxb** [ItsANoBrainer/qb-racing#8] opened 2022-03-21 17:26 UTC
Hi, i have noticed that i am unable to participate in any tracks on my own that i haven't made, if i made the track i can race it on my own, if i have not made it i am unable to start this track is this an issue or is this something that can be resolved i have checked configs but cannot see a minimum racers option

**Comment by ItsANoBrainer** [comment] 2022-03-21 17:36
Duplicate of https://github.com/ItsANoBrainer/qb-racing/issues/7

**Closed as completed by ItsANoBrainer** 2022-03-21 17:36 UTC
